#!/bin/bash
str=$1
pandoc -s -N ${str%.*}.md -o ${str%.*}.pdf -V documentclass=ltjarticle \
--pdf-engine=lualatex --listings -H /config/listings-setup.tex \
-F pandoc-crossref  \
-M "crossrefYaml=/config/crossref_config.yaml"
